name: Link Snitch

on:
  push:
    branches:
      - master

env:
  URL: https://cortex.shadow.coffee
  #FILENAME: report.yaml
  CONFIG: link-snitch-config.json

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Check out master
        uses: actions/checkout@master
        with:
          fetch-depth: 1
      - name: Report broken links
        uses: victoriadrake/link-snitch@master
